[package]
name = "poetic_interpreter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.release]
lto = true
codegen-units = 1

[dependencies]
poetic = {path = "../poetic"}
atty = "0.2"
structopt = "0.3"
